#spring.application.name=student-collabration-platform
#spring.datasource.url=jdbc:postgresql://iit-itm-scp.c7i0w4iemdkg.us-east-2.rds.amazonaws.com:5432/iit-itm-scp

#spring.datasource.username=postgres
#spring.datasource.password=Fall2025websys
#spring.jpa.hibernate.ddl-auto=update

okta.client.orgUrl=https://integrator-7966481.okta.com
okta.client.token=00RSWlN0c0KYJE81Q3RilJQ2nPdFQPdKrn3Iv_mQ0d



spring.application.name=student-collabration-platform
spring.datasource.url=jdbc:postgresql://localhost:5432/abodhale
spring.datasource.username=abodhale
spring.datasource.password= Akash3011@
spring.jpa.hibernate.ddl-auto=update